name: Node CI

on:
  push:
    branches:
      - master
      - staging

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: yarn install build ios android
        run: |
          yarn
          yarn global add expo-cli
          expo build:ios
          expo build:android -t app-bundle
        env:
          CI: true
