version: 2.1

executors:
  default:
    docker:
      - image: circleci/node:12

  android:
    docker:
      - image: circleci/android:api-29-node

  ios:
    macos:
      xcode: "11.3"

commands:
  restore_yarn:
    steps:
      - restore_cache:
          name: Yarn パッケージキャッシュを復元
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}

  save_yarn:
    steps:
      - save_cache:
          name: Yarn パッケージキャッシュを保存
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/project/node_modules
            - ~/.cache/yarn

jobs:
  setup:
    executor:
      name: default
    steps:
      - checkout
      - restore_yarn
      - run:
          name: 依存関係をインストール
          command: yarn install --frozen-lockfile
      - save_yarn

  publish:
    executor:
      name: default
    steps:
      - checkout
      - restore_yarn
      - run:
          name: login
          command: ~/project/node_modules/expo-cli/bin/expo.js login -u $username -p $password
      - run:
          name: publish
          command: ~/project/node_modules/expo-cli/bin/expo.js publish

workflows:
  android-ios:
    jobs:
      - setup
      - publish:
          requires:
            - setup
