name: build android aab

on:
  push:
    branches:
      - staging
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v1
      - name: Setup kernel for react native, increase watchers
        run: echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: yarn install build ios
        run: |
          yarn
          node_modules/expo-cli/bin/expo.js login -u $USERNAME -p $PASSOWRD
          node_modules/expo-cli/bin/expo.js buld:android -t app-bundle
        env:
          CI: true
          USERNAME: ${{ secrets.expo_username}}
          $PASSOWRD: ${{ secrets.expo_password}}
