name: Node CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: yarn install build ios android
        run: |
          yarn
          node_modules/expo-cli/bin/expo.js login -u $USERNAME -p $PASSOWRD
          node_modules/expo-cli/bin/expo.js publish
        env:
          CI: true
          USERNAME: ${{ secrets.expo_username}}
          PASSWORD: ${{ secrets.expo_password }}
